version: "3.8"

services:

  gunicorn_server:
    build: ./
    ports:
      - "8000:8000"

  nginx_server:
    image: nginx:1.22.0-alpine
    ports:
      - "80:80"
    volumes:
      - ./static/:/usr/share/nginx/html/
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
