# Generated by Django 4.0.4 on 2022-06-01 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_system_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.category'),
        ),
        migrations.AlterField(
            model_name='system',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='./static/images/', verbose_name='Official Logo'),
        ),
    ]
