# Generated by Django 4.0.4 on 2022-06-01 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_system_category_alter_system_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='system',
            name='category',
        ),
        migrations.AddField(
            model_name='system',
            name='categories',
            field=models.ManyToManyField(to='api.category'),
        ),
    ]
