# Generated by Django 4.0.4 on 2022-06-01 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_system_category_system_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='name',
            field=models.CharField(max_length=32, verbose_name='Operating system'),
        ),
    ]
