# Generated by Django 4.0.4 on 2022-06-01 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_system_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='system',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Operating system'),
        ),
    ]
