version: "3.8"


volumes:
  static_data:
  postgres_data:


services:
  postgres_database:
    image: postgres:14.3-alpine3.16
    environment:
      PGDATA: ${POSTGRES_DATA_PATH}
      POSTGRES_DB: ${POSTGRES_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  django_application:
    build: ./
    environment:
      POSTGRES_NAME: ${POSTGRES_NAME}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_ENGINE: ${POSTGRES_ENGINE}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DJANGO_SUPERUSER_EMAIL: ${DJANGO_SUPERUSER_EMAIL}
      DJANGO_SUPERUSER_USERNAME: ${DJANGO_SUPERUSER_USERNAME}
      DJANGO_SUPERUSER_PASSWORD: ${DJANGO_SUPERUSER_PASSWORD}
      S3_BUCKET_NAME: ${S3_BUCKET_NAME}
      S3_ENDPOINT_URL: ${S3_ENDPOINT_URL}
      S3_FILE_STORAGE: ${S3_FILE_STORAGE}
      S3_ACCESS_KEY_ID: ${S3_ACCESS_KEY_ID}
      S3_SECRET_ACCESS_KEY: ${S3_SECRET_ACCESS_KEY}
    depends_on:
      - postgres_database
    ports:
      - "8000:8000"
    volumes:
      - static_data:/home/my_os/static/
      - ./my_os/api/migrations/:/home/my_os/api/migrations/
    command: sh -c "python3 ./manage.py makemigrations
                 && python3 ./manage.py migrate
                 && python3 ./manage.py shell < ./create_superuser.py
                 && gunicorn -b 0.0.0.0:8000 my_os.wsgi:application"

  nginx_server:
    image: nginx:1.22.0-alpine
    depends_on:
      - django_application
    ports:
      - "80:80"
    volumes:
      - static_data:/home/my_os/static/
      - ./nginx/cache/:/data/nginx/cache/
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
